apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: kube-prometheus-stack
  namespace: argocd

spec:
  project: default

  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 91.7.0

    helm:
      releaseName: monitoring
      valueFiles:
        - $values/infrastructure/kube-prometheus-stack/values.yaml

  - repoURL: https://github.com/bhuvan-b/trade-risk-monitor.git
    targetRevision: 03_EKS_Setup
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true