grafana:
  enabled: true
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: true

prometheus:
  enabled: true
  prometheusSpec:
    externalUrl: "http://k8s-monitori-monitori-b476036113-1946841608.eu-west-1.elb.amazonaws.com/prometheus/"
    routePrefix: "/prometheus"

alertmanager:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true